from __future__ import annotations

from xml.sax.saxutils import escape, quoteattr

from image2dng import __version__
from image2dng.models import AIMetadataModel

XMP_AI_NAMESPACE = "https://example.org/ns/xmp/ai/1.0/"


def build_xmp_packet(ai: AIMetadataModel) -> bytes:
    attrs = {
        "xmp:CreatorTool": f"image2dng {__version__}",
        "xmpAI:provenanceType": ai.provenance_type,
        "xmpAI:modelName": ai.model_name,
        "xmpAI:modelVersion": ai.model_version,
        "xmpAI:promptHash": ai.prompt_hash,
        "xmpAI:sceneDescription": ai.scene_description,
        "xmpAI:lighting": ai.lighting,
        "xmpAI:weather": ai.weather,
        "xmpAI:cameraParametersAreSimulated": str(ai.camera_parameters_are_simulated),
        "xmpAI:rawMode": ai.raw_mode,
    }
    if ai.iso is not None:
        attrs["xmpAI:simulatedISO"] = str(ai.iso)
    if ai.white_balance_kelvin is not None:
        attrs["xmpAI:simulatedWhiteBalanceKelvin"] = f"{ai.white_balance_kelvin:g}"
    if ai.cfa_pattern is not None:
        attrs["xmpAI:cfaPattern"] = ai.cfa_pattern
    if ai.sensor_noise_model is not None:
        attrs["xmpAI:sensorNoiseModel"] = ai.sensor_noise_model
    if ai.shot_noise is not None:
        attrs["xmpAI:shotNoise"] = f"{ai.shot_noise:g}"
    if ai.read_noise is not None:
        attrs["xmpAI:readNoise"] = f"{ai.read_noise:g}"
    if ai.row_noise is not None:
        attrs["xmpAI:rowNoise"] = f"{ai.row_noise:g}"
    if ai.sensor_effect_seed is not None:
        attrs["xmpAI:sensorEffectSeed"] = str(ai.sensor_effect_seed)
    if ai.highlight_headroom_ev is not None:
        attrs["xmpAI:highlightHeadroomEV"] = f"{ai.highlight_headroom_ev:g}"
    if ai.exposure_bias_ev is not None:
        attrs["xmpAI:exposureBiasEV"] = f"{ai.exposure_bias_ev:g}"
    if ai.prompt_plaintext is not None:
        attrs["xmpAI:promptPlaintext"] = ai.prompt_plaintext

    attr_text = "\n      ".join(f"{name}={quoteattr(value)}" for name, value in attrs.items())
    description = escape(ai.scene_description or "Synthetic image generated by image2dng")
    packet = f'''<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description
      rdf:about=""
      xmlns:xmp="http://ns.adobe.com/xap/1.0/"
      xmlns:dc="http://purl.org/dc/elements/1.1/"
      xmlns:xmpAI="{XMP_AI_NAMESPACE}"
      {attr_text}>
      <dc:description>
        <rdf:Alt>
          <rdf:li xml:lang="x-default">{description}</rdf:li>
        </rdf:Alt>
      </dc:description>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>'''
    return packet.encode("utf-8")
